// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZUK7Jkbb982sWXS1RjBuAEGP6l8RMf04',
    appId: '1:284279273330:web:1d92d67d005599c7624feb',
    messagingSenderId: '284279273330',
    projectId: 'gottani-2025',
    authDomain: 'gottani-2025.firebaseapp.com',
    storageBucket: 'gottani-2025.firebasestorage.app',
    measurementId: 'G-JL1GFRCWTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdQHDQYsAIL0bBVom2zpAw9_LNd1-pbG8',
    appId: '1:284279273330:android:32a6b9a71a0f2cf3624feb',
    messagingSenderId: '284279273330',
    projectId: 'gottani-2025',
    storageBucket: 'gottani-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd-g9LN5Y5lHzp3pHlYpWFLNjPmUaIj-w',
    appId: '1:284279273330:ios:733f389b6edc6d4b624feb',
    messagingSenderId: '284279273330',
    projectId: 'gottani-2025',
    storageBucket: 'gottani-2025.firebasestorage.app',
    iosBundleId: 'com.example.gottani.template',
  );
}
